"""
solomon.py
-----------
Load Solomon's CVRPTW benchmark instances, so the optimiser can be measured
against results the field already agrees on.

Why this exists
===============
Everything else here compares QPSO to baselines written in this repo, on
instances generated by this repo. That answers "which of ours is best", which
is a different question from "is any of this any good". exact_vrp.py closed
that gap for instances up to ten customers by proving the optimum; past that
size nothing did.

Solomon's 1987 set is the standard CVRPTW benchmark. Its instances have been
attacked for nearly forty years and their best-known solutions are published,
so "within X% of best known on R101" is a claim an operations-research reader
can place immediately, and one no amount of self-comparison substitutes for.

The three families differ in how customers are spread, which is the point of
running more than one:

    C  clustered          customers in tight groups
    R  random             uniformly scattered
    RC mixed              half clustered, half random

and the second digit is the horizon: 1xx are short (tight windows, many
vehicles), 2xx are long (loose windows, few vehicles carrying more each).

What the instance says, and what this project usually assumes
=============================================================
Two differences matter, and both are handled here rather than papered over:

1. Solomon is Euclidean and untimed. Travel time equals Euclidean distance
   between coordinates -- no road network, no congestion, no time-of-day. So
   the loader builds a complete graph over the instance's points at unit speed
   and leaves time_dependent off. Applying this project's congestion model to a
   Solomon instance would produce numbers that cannot be compared with anything
   published.

2. Solomon is scored on distance alone (after minimising vehicles), not on the
   time/distance blend this project's own objective uses. The loaded problem
   therefore carries objective_w_time=0.0 and objective_w_distance=1.0, which
   every solver here picks up through evaluate_solution. Optimising one
   objective and reporting the gap against another would measure the
   disagreement between the two, not the quality of the search.

Distances are kept as exact floats. Some of the literature truncates them to
one decimal, which shifts reported totals slightly; the gap is reported against
best-known values quoted to the same convention used here, and any comparison
at the third decimal place should be treated as noise rather than signal.
"""

from __future__ import annotations

import math
import os
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

from app.core.graph_model import TrafficNetwork
from app.core.vrp_problem import Customer, VRPProblem

INSTANCE_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "data", "benchmarks", "solomon",
)


# Best-known total distance for the 100-customer instances, with the vehicle
# count they are achieved with. Solomon's objective is hierarchical: fewest
# vehicles first, then shortest distance -- so a solution using more vehicles
# does not beat one of these however short it is, and the loader reports both.
#
# These are the long-standing published figures for the set; several have been
# proven optimal. They are quoted here rather than fetched so the benchmark
# runs offline and so a number cannot change underneath a published result.
BEST_KNOWN: Dict[str, Tuple[int, float]] = {
    "C101": (10, 827.3),
    "C201": (3, 589.1),
    "R101": (19, 1650.8),
    "R201": (4, 1252.37),
    "RC101": (14, 1696.95),
    "RC201": (4, 1406.94),
}


@dataclass
class SolomonInstance:
    """One parsed instance, before it becomes a VRPProblem."""

    name: str
    n_vehicles: int
    capacity: float
    # index 0 is the depot; the rest are customers, in file order
    x: List[float]
    y: List[float]
    demand: List[float]
    ready: List[float]
    due: List[float]
    service: List[float]

    @property
    def n_customers(self) -> int:
        return len(self.x) - 1


class SolomonParseError(ValueError):
    """The file was not in Solomon's format."""


def parse_solomon(text: str, name: Optional[str] = None) -> SolomonInstance:
    """
    Parse Solomon's fixed layout: a name, a VEHICLE block giving fleet size and
    capacity, then a CUSTOMER table of
    `id x y demand ready due service`, depot first.

    Column positions are not relied on. The files in circulation differ in
    spacing and in header wording, and several have trailing blank or partial
    lines, so rows are taken as "seven numbers on a line" instead.
    """
    lines = text.splitlines()
    instance_name = name
    n_vehicles: Optional[int] = None
    capacity: Optional[float] = None
    rows: List[List[float]] = []

    in_vehicle_block = False
    for raw in lines:
        line = raw.strip()
        if not line:
            continue
        upper = line.upper()

        if instance_name is None and not upper.startswith(("VEHICLE", "CUSTOMER")):
            instance_name = line.split()[0]
            continue
        if upper.startswith("VEHICLE"):
            in_vehicle_block = True
            continue
        if upper.startswith("CUSTOMER"):
            in_vehicle_block = False
            continue
        if upper.startswith(("NUMBER", "CUST")):
            continue

        parts = line.split()
        try:
            numbers = [float(p) for p in parts]
        except ValueError:
            continue                      # a header this parser does not know

        if in_vehicle_block and len(numbers) == 2:
            n_vehicles, capacity = int(numbers[0]), numbers[1]
            in_vehicle_block = False
        elif len(numbers) >= 7:
            rows.append(numbers[:7])

    if n_vehicles is None or capacity is None:
        raise SolomonParseError("no VEHICLE block (fleet size and capacity) found")
    if len(rows) < 2:
        raise SolomonParseError(
            f"expected a depot and at least one customer, found {len(rows)} rows"
        )

    return SolomonInstance(
        name=instance_name or "unknown",
        n_vehicles=n_vehicles,
        capacity=capacity,
        x=[r[1] for r in rows],
        y=[r[2] for r in rows],
        demand=[r[3] for r in rows],
        ready=[r[4] for r in rows],
        due=[r[5] for r in rows],
        service=[r[6] for r in rows],
    )


def load_solomon_file(path: str) -> SolomonInstance:
    with open(path, encoding="utf-8") as fh:
        return parse_solomon(fh.read(), name=os.path.splitext(os.path.basename(path))[0])


def available_instances() -> List[str]:
    """Instance names shipped with the repo, upper-cased, sorted."""
    if not os.path.isdir(INSTANCE_DIR):
        return []
    return sorted(
        os.path.splitext(f)[0].upper()
        for f in os.listdir(INSTANCE_DIR)
        if f.lower().endswith(".txt")
    )


def _euclidean_network(inst: SolomonInstance) -> Tuple[TrafficNetwork, List[int]]:
    """
    A complete graph over the instance's points, at unit speed so travel time
    equals Euclidean distance -- which is Solomon's convention, and the only
    one under which the published figures mean anything.
    """
    net = TrafficNetwork()
    node_ids = list(range(len(inst.x)))
    for i in node_ids:
        net.add_node(i, x=inst.x[i], y=inst.y[i])

    for i in node_ids:
        for j in node_ids:
            if i == j:
                continue
            d = math.hypot(inst.x[i] - inst.x[j], inst.y[i] - inst.y[j])
            # base_speed 60 km/h turns minutes into units 1:1 in this model's
            # arithmetic (base_time = distance / speed * 60), so a unit of
            # distance costs a unit of time, as Solomon intends.
            net.add_edge(i, j, distance=d, base_speed_kmph=60.0,
                         congestion_factor=1.0, bidirectional=False)
    return net, node_ids


def to_vrp_problem(inst: SolomonInstance, n_vehicles: Optional[int] = None) -> VRPProblem:
    """
    Turn a parsed instance into the VRPProblem the solvers here take.

    `n_vehicles` defaults to the fleet the file declares, which for the
    100-customer set is 25 -- a ceiling, not a target. Solomon's objective
    minimises vehicles first, and leaving vans parked is already the cheaper
    option under this project's scoring, so the ceiling is passed through
    unchanged rather than tightened to the best-known count. Tightening it
    would hand the solver the answer to half the problem.
    """
    net, _ = _euclidean_network(inst)
    customers = [
        Customer(
            node_id=i,
            demand=inst.demand[i],
            ready_time=inst.ready[i],
            due_time=inst.due[i],
            service_time=inst.service[i],
        )
        for i in range(1, len(inst.x))
    ]

    return VRPProblem(
        net=net,
        depot=0,
        customers=customers,
        vehicle_capacity=inst.capacity,
        n_vehicles=n_vehicles if n_vehicles is not None else inst.n_vehicles,
        # Solomon is untimed: one distance matrix, no congestion curve. Leaving
        # this on would price every leg against a commuter peak the benchmark
        # knows nothing about.
        time_dependent=False,
        # ... and scored on distance alone.
        objective_w_time=0.0,
        objective_w_distance=1.0,
    )


def load_problem(name: str, n_vehicles: Optional[int] = None) -> VRPProblem:
    """Load a shipped instance by name, e.g. load_problem("R101")."""
    path = os.path.join(INSTANCE_DIR, f"{name.upper()}.txt")
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"No Solomon instance {name!r} in {INSTANCE_DIR}. "
            f"Available: {', '.join(available_instances()) or '(none)'}"
        )
    return to_vrp_problem(load_solomon_file(path), n_vehicles=n_vehicles)


def best_known(name: str) -> Optional[Tuple[int, float]]:
    """(vehicles, distance) for an instance, or None if not recorded here."""
    return BEST_KNOWN.get(name.upper())
